import type { ActionKind, Language } from "../domain/models";

export interface Dictionary {
  appName: string;
  tagline: string;
  dashboard: string;
  inventory: string;
  itemManagement: string;
  refillOrders: string;
  alerts: string;
  personnel: string;
  settings: string;
  currentInventoryLevels: string;
  inventoryOperationsHint: string;
  manageItemsHint: string;
  currentQuantityManagedHint: string;
  totalItems: string;
  totalUnits: string;
  lowStock: string;
  outOfStock: string;
  openAlerts: string;
  pendingRefillOrders: string;
  sku: string;
  itemName: string;
  category: string;
  location: string;
  currentQuantity: string;
  unit: string;
  reorderLevel: string;
  status: string;
  lastUpdated: string;
  supplier: string;
  orderNumber: string;
  orderDate: string;
  expectedDelivery: string;
  receivedDate: string;
  totalAmount: string;
  createdBy: string;
  backupPlan: string;
  targetPath: string;
  targetType: string;
  schedule: string;
  retention: string;
  lastBackup: string;
  nextBackup: string;
  language: string;
  backupReady: string;
  needsAttention: string;
  createItem: string;
  modifyItem: string;
  receiveStock: string;
  issueMaterial: string;
  createRefillOrder: string;
  removeItem: string;
  manage: string;
  loadingWorkspace: string;
  noInventoryItems: string;
  noInventoryItemsHint: string;
  noRefillOrders: string;
  noRefillOrdersHint: string;
  noAlerts: string;
  noAlertsHint: string;
  backupStorageHint: string;
  backupNotConfigured: string;
  managePersonnelHint: string;
  personnelName: string;
  addPersonnel: string;
  removePersonnel: string;
  noPersonnel: string;
  noPersonnelHint: string;
  selectPersonnel: string;
  personnelRequiredHint: string;
  notAvailable: string;
  cancel: string;
  save: string;
  quantity: string;
  reason: string;
  performedBy: string;
  initialQuantity: string;
  selectItem: string;
  selectItemToRemove: string;
  unitCost: string;
  optionalField: string;
  autoGeneratedIfBlank: string;
  addNewCategory: string;
  newCategoryName: string;
  deleteItemWarning: string;
  deleteItemImpact: string;
  actionPanelTitle: Record<ActionKind, string>;
  actionPanelHint: Record<ActionKind, string>;
  successCreateItem: string;
  successUpdateItem: string;
  successReceiveStock: string;
  successIssueMaterial: string;
  successCreateRefillOrder: string;
  successRemoveItem: string;
  successAddPersonnel: string;
  successRemovePersonnel: string;
  lowStockAlertIssued: (itemName: string, sku: string, currentQuantity: number, thresholdQuantity: number) => string;
  formValidationError: string;
}

export const dictionaries: Record<Language, Dictionary> = {
  en: {
    appName: "Inventory Monitor",
    tagline: "Local-first inventory control with refill tracking and backup readiness.",
    dashboard: "Dashboard",
    inventory: "Inventory",
    itemManagement: "Item Management",
    refillOrders: "Refill Orders",
    alerts: "Alerts",
    personnel: "Personnel",
    settings: "Settings",
    currentInventoryLevels: "Current Inventory Levels",
    inventoryOperationsHint: "Receive and issue stock from the live inventory list.",
    manageItemsHint: "Create, modify, and delete item records only in this page.",
    currentQuantityManagedHint: "Current quantity is managed through Receive Stock and Issue Material, not through item editing.",
    totalItems: "Total Items",
    totalUnits: "Total Units",
    lowStock: "Low Stock",
    outOfStock: "Out Of Stock",
    openAlerts: "Open Alerts",
    pendingRefillOrders: "Pending Refill Orders",
    sku: "SKU",
    itemName: "Item Name",
    category: "Category",
    location: "Location",
    currentQuantity: "Current Quantity",
    unit: "Unit",
    reorderLevel: "Reorder Level",
    status: "Status",
    lastUpdated: "Last Updated",
    supplier: "Supplier",
    orderNumber: "Order No.",
    orderDate: "Order Date",
    expectedDelivery: "Expected Delivery",
    receivedDate: "Received Date",
    totalAmount: "Total Amount",
    createdBy: "Created By",
    backupPlan: "Backup Plan",
    targetPath: "Target Path",
    targetType: "Target Type",
    schedule: "Schedule",
    retention: "Retention",
    lastBackup: "Last Backup",
    nextBackup: "Next Backup",
    language: "Language",
    backupReady: "Backup target validated",
    needsAttention: "Needs attention",
    createItem: "Create Item",
    modifyItem: "Modify Item",
    receiveStock: "Receive Stock",
    issueMaterial: "Issue Material",
    createRefillOrder: "Create Refill Order",
    removeItem: "Remove Item",
    manage: "Manage",
    loadingWorkspace: "Loading inventory workspace...",
    noInventoryItems: "No inventory records yet.",
    noInventoryItemsHint: "Create the first item to start tracking on-hand quantity and low-stock rules.",
    noRefillOrders: "No refill orders recorded.",
    noRefillOrdersHint: "Create a refill order when inventory purchases need to be logged.",
    noAlerts: "No low-stock alerts.",
    noAlertsHint: "Alerts will appear when an item reaches or drops below its reorder level.",
    backupStorageHint: "Local database backups can be stored on LAN shares or cloud-synced folders.",
    backupNotConfigured: "Backup destination not configured yet.",
    managePersonnelHint: "Manage the operator list used by stock movement forms.",
    personnelName: "Personnel Name",
    addPersonnel: "Add Personnel",
    removePersonnel: "Remove",
    noPersonnel: "No personnel records yet.",
    noPersonnelHint: "Add personnel before recording stock movements so Performed By can be selected from a list.",
    selectPersonnel: "Select Personnel",
    personnelRequiredHint: "Add at least one personnel record before receiving or issuing stock.",
    notAvailable: "Not configured",
    cancel: "Cancel",
    save: "Save",
    quantity: "Quantity",
    reason: "Reason",
    performedBy: "Performed By",
    initialQuantity: "Initial Quantity",
    selectItem: "Select Item",
    selectItemToRemove: "Select Item To Remove",
    unitCost: "Unit Cost",
    optionalField: "Optional",
    autoGeneratedIfBlank: "Auto-generated if blank",
    addNewCategory: "Add New Category",
    newCategoryName: "New Category Name",
    deleteItemWarning: "This permanently removes the item from inventory management.",
    deleteItemImpact: "Related stock movements, alerts, and refill-order lines for this item will also be removed. Refill orders with no remaining lines will be deleted.",
    actionPanelTitle: {
      createItem: "Create Inventory Item",
      modifyItem: "Modify Inventory Item",
      receiveStock: "Receive Stock",
      issueMaterial: "Issue Material",
      createRefillOrder: "Create Refill Order",
      removeItem: "Remove Inventory Item",
    },
    actionPanelHint: {
      createItem: "Register a new inventory record with on-hand quantity and reorder thresholds.",
      modifyItem: "Update item master data without changing the on-hand quantity.",
      receiveStock: "Add materials into inventory and refresh the current quantity immediately.",
      issueMaterial: "Remove materials from inventory and evaluate low-stock alerts.",
      createRefillOrder: "Record a purchase order before stock is physically received.",
      removeItem: "Remove an item and its related operational records from the inventory database.",
    },
    successCreateItem: "Inventory item created.",
    successUpdateItem: "Inventory item updated.",
    successReceiveStock: "Stock receipt recorded.",
    successIssueMaterial: "Material issue recorded.",
    successCreateRefillOrder: "Refill order created.",
    successRemoveItem: "Inventory item removed.",
    successAddPersonnel: "Personnel added.",
    successRemovePersonnel: "Personnel removed.",
    lowStockAlertIssued: (itemName: string, sku: string, currentQuantity: number, thresholdQuantity: number) =>
      `Low-stock alert issued for ${itemName} (${sku}). Current quantity is ${currentQuantity}, reorder level is ${thresholdQuantity}.`,
    formValidationError: "Check the required fields and quantity values.",
  },
  "zh-CN": {
    appName: "\u5e93\u5b58\u76d1\u63a7",
    tagline: "\u652f\u6301\u8865\u8d27\u8ba2\u5355\u3001\u4f4e\u5e93\u5b58\u9884\u8b66\u548c\u5907\u4efd\u7ba1\u7406\u7684\u672c\u5730\u5e93\u5b58\u7cfb\u7edf\u3002",
    dashboard: "\u6982\u89c8",
    inventory: "\u5e93\u5b58",
    itemManagement: "\u7269\u6599\u7ba1\u7406",
    refillOrders: "\u8865\u8d27\u8ba2\u5355",
    alerts: "\u9884\u8b66",
    personnel: "\u4eba\u5458\u7ba1\u7406",
    settings: "\u8bbe\u7f6e",
    currentInventoryLevels: "\u5f53\u524d\u5e93\u5b58\u6c34\u5e73",
    inventoryOperationsHint: "\u5728\u5f53\u524d\u5e93\u5b58\u5217\u8868\u4e2d\u6267\u884c\u5165\u5e93\u548c\u51fa\u5e93\u64cd\u4f5c\u3002",
    manageItemsHint: "\u53ea\u5728\u6b64\u9875\u9762\u521b\u5efa\u3001\u4fee\u6539\u548c\u5220\u9664\u7269\u6599\u8bb0\u5f55\u3002",
    currentQuantityManagedHint: "\u5f53\u524d\u6570\u91cf\u901a\u8fc7\u5165\u5e93\u548c\u51fa\u5e93\u7ba1\u7406\uff0c\u4e0d\u5728\u7269\u6599\u7f16\u8f91\u4e2d\u4fee\u6539\u3002",
    totalItems: "\u7269\u6599\u603b\u6570",
    totalUnits: "\u5e93\u5b58\u603b\u91cf",
    lowStock: "\u4f4e\u5e93\u5b58",
    outOfStock: "\u7f3a\u8d27",
    openAlerts: "\u672a\u5904\u7406\u9884\u8b66",
    pendingRefillOrders: "\u5f85\u5b8c\u6210\u8865\u8d27\u5355",
    sku: "SKU",
    itemName: "\u7269\u6599\u540d\u79f0",
    category: "\u7c7b\u522b",
    location: "\u4f4d\u7f6e",
    currentQuantity: "\u5f53\u524d\u6570\u91cf",
    unit: "\u5355\u4f4d",
    reorderLevel: "\u8865\u8d27\u91cf",
    status: "\u72b6\u6001",
    lastUpdated: "\u6700\u540e\u66f4\u65b0",
    supplier: "\u4f9b\u5e94\u5546",
    orderNumber: "\u8ba2\u5355\u53f7",
    orderDate: "\u4e0b\u5355\u65e5\u671f",
    expectedDelivery: "\u9884\u8ba1\u5230\u8d27",
    receivedDate: "\u6536\u8d27\u65e5\u671f",
    totalAmount: "\u603b\u91d1\u989d",
    createdBy: "\u521b\u5efa\u4eba",
    backupPlan: "\u5907\u4efd\u65b9\u6848",
    targetPath: "\u76ee\u6807\u8def\u5f84",
    targetType: "\u76ee\u6807\u7c7b\u578b",
    schedule: "\u8ba1\u5212",
    retention: "\u4fdd\u7559\u7b56\u7565",
    lastBackup: "\u4e0a\u6b21\u5907\u4efd",
    nextBackup: "\u4e0b\u6b21\u5907\u4efd",
    language: "\u8bed\u8a00",
    backupReady: "\u5907\u4efd\u76ee\u6807\u5df2\u9a8c\u8bc1",
    needsAttention: "\u9700\u8981\u5904\u7406",
    createItem: "\u65b0\u589e\u7269\u6599",
    modifyItem: "\u4fee\u6539\u7269\u6599",
    receiveStock: "\u5165\u5e93",
    issueMaterial: "\u51fa\u5e93",
    createRefillOrder: "\u521b\u5efa\u8865\u8d27\u5355",
    removeItem: "\u79fb\u9664\u7269\u6599",
    manage: "\u7ba1\u7406",
    loadingWorkspace: "\u6b63\u5728\u52a0\u8f7d\u5e93\u5b58\u5de5\u4f5c\u533a...",
    noInventoryItems: "\u8fd8\u6ca1\u6709\u5e93\u5b58\u8bb0\u5f55\u3002",
    noInventoryItemsHint: "\u5148\u521b\u5efa\u7b2c\u4e00\u4e2a\u7269\u6599\uff0c\u518d\u5f00\u59cb\u8ddf\u8e2a\u73b0\u5b58\u6570\u91cf\u548c\u4f4e\u5e93\u5b58\u89c4\u5219\u3002",
    noRefillOrders: "\u8fd8\u6ca1\u6709\u8865\u8d27\u8ba2\u5355\u3002",
    noRefillOrdersHint: "\u9700\u8981\u8bb0\u5f55\u91c7\u8d2d\u65f6\uff0c\u521b\u5efa\u4e00\u5f20\u8865\u8d27\u5355\u3002",
    noAlerts: "\u76ee\u524d\u6ca1\u6709\u4f4e\u5e93\u5b58\u9884\u8b66\u3002",
    noAlertsHint: "\u5f53\u7269\u6599\u6570\u91cf\u964d\u5230\u6216\u4f4e\u4e8e\u8865\u8d27\u91cf\u65f6\uff0c\u9884\u8b66\u4f1a\u51fa\u73b0\u5728\u8fd9\u91cc\u3002",
    backupStorageHint: "\u672c\u5730\u6570\u636e\u5e93\u5907\u4efd\u53ef\u4ee5\u4fdd\u5b58\u5230 LAN \u5171\u4eab\u6216\u4e91\u540c\u6b65\u6587\u4ef6\u5939\u3002",
    backupNotConfigured: "\u8fd8\u672a\u914d\u7f6e\u5907\u4efd\u76ee\u6807\u3002",
    managePersonnelHint: "\u7ba1\u7406\u5e93\u5b58\u64cd\u4f5c\u8868\u5355\u4f7f\u7528\u7684\u4eba\u5458\u5217\u8868\u3002",
    personnelName: "\u4eba\u5458\u59d3\u540d",
    addPersonnel: "\u65b0\u589e\u4eba\u5458",
    removePersonnel: "\u79fb\u9664",
    noPersonnel: "\u8fd8\u6ca1\u6709\u4eba\u5458\u8bb0\u5f55\u3002",
    noPersonnelHint: "\u5148\u65b0\u589e\u4eba\u5458\uff0c\u518d\u8bb0\u5f55\u5165\u5e93\u6216\u51fa\u5e93\uff0c\u8fd9\u6837\u201c\u64cd\u4f5c\u4eba\u201d\u53ef\u4ee5\u4ece\u5217\u8868\u9009\u62e9\u3002",
    selectPersonnel: "\u9009\u62e9\u4eba\u5458",
    personnelRequiredHint: "\u8bf7\u5148\u65b0\u589e\u81f3\u5c11\u4e00\u540d\u4eba\u5458\uff0c\u518d\u8fdb\u884c\u5165\u5e93\u6216\u51fa\u5e93\u3002",
    notAvailable: "\u672a\u914d\u7f6e",
    cancel: "\u53d6\u6d88",
    save: "\u4fdd\u5b58",
    quantity: "\u6570\u91cf",
    reason: "\u539f\u56e0",
    performedBy: "\u64cd\u4f5c\u4eba",
    initialQuantity: "\u521d\u59cb\u6570\u91cf",
    selectItem: "\u9009\u62e9\u7269\u6599",
    selectItemToRemove: "\u9009\u62e9\u8981\u79fb\u9664\u7684\u7269\u6599",
    unitCost: "\u5355\u4ef7",
    optionalField: "\u53ef\u9009",
    autoGeneratedIfBlank: "\u7559\u7a7a\u65f6\u81ea\u52a8\u751f\u6210",
    addNewCategory: "\u65b0\u589e\u7c7b\u522b",
    newCategoryName: "\u65b0\u7c7b\u522b\u540d\u79f0",
    deleteItemWarning: "\u8fd9\u4f1a\u5c06\u8be5\u7269\u6599\u4ece\u5e93\u5b58\u7ba1\u7406\u4e2d\u6c38\u4e45\u79fb\u9664\u3002",
    deleteItemImpact: "\u8be5\u7269\u6599\u7684\u5e93\u5b58\u53d8\u52a8\u3001\u9884\u8b66\u3001\u8865\u8d27\u8ba2\u5355\u660e\u7ec6\u4e5f\u4f1a\u88ab\u5220\u9664\u3002\u5982\u679c\u8865\u8d27\u5355\u6ca1\u6709\u5269\u4f59\u660e\u7ec6\uff0c\u8be5\u8865\u8d27\u5355\u4e5f\u4f1a\u88ab\u5220\u9664\u3002",
    actionPanelTitle: {
      createItem: "\u65b0\u589e\u5e93\u5b58\u7269\u6599",
      modifyItem: "\u4fee\u6539\u5e93\u5b58\u7269\u6599",
      receiveStock: "\u8bb0\u5f55\u5165\u5e93",
      issueMaterial: "\u8bb0\u5f55\u51fa\u5e93",
      createRefillOrder: "\u521b\u5efa\u8865\u8d27\u5355",
      removeItem: "\u79fb\u9664\u5e93\u5b58\u7269\u6599",
    },
    actionPanelHint: {
      createItem: "\u521b\u5efa\u65b0\u5e93\u5b58\u8bb0\u5f55\uff0c\u5e76\u8bbe\u5b9a\u73b0\u6709\u6570\u91cf\u4e0e\u8865\u8d27\u9608\u503c\u3002",
      modifyItem: "\u66f4\u65b0\u7269\u6599\u4e3b\u6570\u636e\uff0c\u4e0d\u6539\u53d8\u5f53\u524d\u5e93\u5b58\u6570\u91cf\u3002",
      receiveStock: "\u5c06\u6750\u6599\u5165\u5e93\uff0c\u5e76\u7acb\u5373\u66f4\u65b0\u5f53\u524d\u5e93\u5b58\u6570\u91cf\u3002",
      issueMaterial: "\u4ece\u5e93\u5b58\u4e2d\u9886\u7528\u6750\u6599\uff0c\u5e76\u68c0\u67e5\u4f4e\u5e93\u5b58\u9884\u8b66\u3002",
      createRefillOrder: "\u5728\u7269\u7406\u6536\u8d27\u4e4b\u524d\u5148\u8bb0\u5f55\u91c7\u8d2d\u8ba2\u5355\u3002",
      removeItem: "\u5c06\u7269\u6599\u53ca\u5176\u76f8\u5173\u8fd0\u8425\u8bb0\u5f55\u4ece\u5e93\u5b58\u6570\u636e\u5e93\u4e2d\u5220\u9664\u3002",
    },
    successCreateItem: "\u5df2\u521b\u5efa\u5e93\u5b58\u7269\u6599\u3002",
    successUpdateItem: "\u5df2\u66f4\u65b0\u5e93\u5b58\u7269\u6599\u3002",
    successReceiveStock: "\u5df2\u8bb0\u5f55\u5165\u5e93\u3002",
    successIssueMaterial: "\u5df2\u8bb0\u5f55\u51fa\u5e93\u3002",
    successCreateRefillOrder: "\u5df2\u521b\u5efa\u8865\u8d27\u5355\u3002",
    successRemoveItem: "\u5df2\u79fb\u9664\u5e93\u5b58\u7269\u6599\u3002",
    successAddPersonnel: "\u5df2\u65b0\u589e\u4eba\u5458\u3002",
    successRemovePersonnel: "\u5df2\u79fb\u9664\u4eba\u5458\u3002",
    lowStockAlertIssued: (itemName: string, sku: string, currentQuantity: number, thresholdQuantity: number) =>
      `${itemName} (${sku}) \u5df2\u89e6\u53d1\u4f4e\u5e93\u5b58\u9884\u8b66\u3002\u5f53\u524d\u6570\u91cf\u4e3a ${currentQuantity}\uff0c\u8865\u8d27\u91cf\u4e3a ${thresholdQuantity}\u3002`,
    formValidationError: "\u8bf7\u68c0\u67e5\u5fc5\u586b\u9879\u548c\u6570\u91cf\u8f93\u5165\u3002",
  },
};
